language: java

cache:
  directories:
    - "$HOME/.tsd-cache"
    - "$TRAVIS_BUILD_DIR/manager/ui/hawtio/node_modules"
    - "$HOME/.m2"

before_cache:
  - "rm -rf $HOME/.m2/repository/io/apiman"

services:
  - elasticsearch

before_install:
  - export MAVEN_OPTS="-Xmx512m"
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - echo "Settings XML" && cat ~/.m2/settings.xml
  - echo "node_modules" && echo "$TRAVIS_BUILD_DIR/manager/ui/war/node_modules"
  
jdk:
  - oraclejdk8

notifications:
  irc:
    channels:
      - "chat.freenode.net#apiman"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

matrix:
  include:
    - env: ACTION='-Dapiman-test.type=es -Dapiman.gateway-test.config=servlet-es'
      jdk: oraclejdk8
    - env: ACTION='-Dapiman.gateway-test.config=amg-1'
      jdk: oraclejdk8

install: travis_retry mvn clean install -Dinvoker.skip -Dmaven.javadoc.skip=true -B | egrep -v 'Download|\\[exec\\] [[:digit:]]+/[[:digit:]]+|^[[:space:]]*\\[exec\\][[:space:]]*$' ; [ ${PIPESTATUS[0]} == 0 ];

script: if [[ -v COMMAND ]]; then $COMMAND; else travis_retry mvn test install -B -Dmaven.javadoc.skip=true $ACTION | egrep -v 'Download|\\[exec\\] [[:digit:]]+/[[:digit:]]+|^[[:space:]]*\\[exec\\][[:space:]]*$' ; [ ${PIPESTATUS[0]} == 0 ]; fi
