name: trigger release from file
on:
  push:
    paths:
      - ".github/workflows/RELEASE_VERSION"
jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read-version.outputs.version }}
    steps:
      - name: Checkout Apiman Docker repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven

      - name: "Read release version"
        id: read-version
        run: echo "::set-output name=version::$(cat .github/workflows/RELEASE_VERSION)"

      - name: Update Maven versions, including parent (if version changed)
        run: |
          mvn clean install
          mvnd -ntp -N versions:update-parent -DparentVersion="[${{ env.version }}]" -DgenerateBackupPoms=false
          mvnd -ntp versions:set -DnewVersion="${{ env.version }}" -DgenerateBackupPoms=false -DprocessAllModules=true
          mvn clean install

      - name: Tag release
        run: |
          git tag -f -a -m "Apiman Docker tag release ${{ env.version }}" ${{ env.version }}
          git push origin ${{ env.version }}

      - name: Create GitHub release ${{ env.version }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          name: ${{ env.version }}
          files: |
            docker-compose/target/apiman-docker-compose-${{ env.version }}.zip
          body: |
            Apiman Docker release for Apiman version ${{ env.version }}.
            
            To access the images associated with this build, please look on Apiman's DockerHub or our GHCR registry (GitHub Packages).   

  build:
    needs: read-version
    uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
    secrets: inherit
    with:
      apiman-version: ${{ needs.read-version.outputs.version }}
      push-to-repos: false
      snapshot: false

  deploy:
    needs: [read-version, build]
    uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
    secrets: inherit
    with:
      apiman-version: ${{ needs.read-version.outputs.version }}
      push-to-repos: true
      snapshot: false
