# This is a basic workflow to help you get started with Actions

name: Verify Build Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Builds:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install node modules
        run: npm install --also=dev
      - name: Do local build
        run: npm run-script build
      - name: Do production build
        run: npm run-script build-production
      - name: Do docker image build
        run: docker build -t apiman-devportal:latest .
  Tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install node modules
        run: npm install --also=dev
      - name: Do browser tests
        run: npm run-script test
        env:
          #Uses the default chrome browser from the ubuntu-latest image
          CHROMIUM_BIN: /usr/bin/google-chrome
      - name: Publish unit test results
        #Taken from https://github.com/marketplace/actions/publish-unit-test-results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          files: junit/api-mgmt-dev-portal/*.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false

  Publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.repository_owner == 'Apiman'
    steps:
      # Build and push new Docker images
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Building Docker Images
        run: docker build . --file Dockerfile --tag apiman/developer-portal:latest
      - name: Push The Tagged Docker Images
        run: docker push apiman/developer-portal:latest

